### PR TITLE
feature: add default colors to Chart

### PR DESCRIPTION
**Pull request by kosenda**
Hello 👋
I could not change the background on some charts (`StackedBarChart`, `AreaChart`, `BarChart`, `GroupBarChart`), so I added a set value to change the color.
I would be happy to merge them if you would like!

### CODE REVIEW

**Comment by hi-manshu** [comment]
Hey any reason to close it?

**Comment by kosenda** [comment]
I thought it might be a Pull Request that had been left unattended for about 4 months and possibly offended you ...

**Comment by hi-manshu** [comment]
Ah no no, i was just busy for couple of months. Will starts reviewing again. Pls reopen it

**Comment by kosenda** [comment]
I see...
I will submit a pull request again, please review 🙇.

**Pull request closed without merging**
