### PR TITLE
Fix #9 | Create sample apk on each new release

### LINKED ISSUE #9: Add demo APK link
Add demo apk link in readme file and that should be updated on each release.

### PR DESCRIPTION
**Pull request by yogeshpaliyal**
Fix #9 

By default it will show 404 on click of button but releases after this PR get merged it will work.
Tested on https://github.com/yogeshpaliyal/Charty

### CODE REVIEW

**Comment by yogeshpaliyal** [comment]
@hi-manshu

**Comment by hi-manshu** [comment]
I will have to change it as I think it wont work for me, as this would need a token here and my path! Let me figure that out and then will merge. But thank you for doing this!

**Comment by yogeshpaliyal** [comment]
Oops forgot to change the path, and you don't need to define token explicitly, the token is always stored in secret.

**Comment by yogeshpaliyal** [comment]
Also path fixed, now this will work.

**Review by hi-manshu — APPROVED** [review]

**Pull request merged**
